-- WhatsApp 360dialog per-salon fields
ALTER TABLE "Accounts"
  ADD COLUMN IF NOT EXISTS "WAEnabled"     BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS "WAConnected"   BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS "WAPhoneNumber" VARCHAR(20),
  ADD COLUMN IF NOT EXISTS "WAApiKey"      TEXT,
  ADD COLUMN IF NOT EXISTS "WAChannelId"   VARCHAR(100),
  ADD COLUMN IF NOT EXISTS "WAClientId"    VARCHAR(100);
